### PR TITLE
Adding more documentation for contributers

### PR DESCRIPTION
**Pull request by devonestes**
There was some question about how to make the `config.json` file a bit more
discoverable, so I figured documentation was a good place to start with that.
This way people know what that file is for, know that the order matters, and
also know to add their new exercise to that file when they are adding a new one
to the repo.

This addresses [this comment](https://github.com/exercism/xelixir/pull/184#discussion_r64992425) by @kytrinyx.

### CODE REVIEW

**Comment by kytrinyx** [comment]
We have a Contributor guide that we try to point people to. What do you think we can do to make the guide easier to understand / the config thing more discoverable there? https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md

Is the problem that people don't read the guide (perhaps because it's so long)?

**Comment by devonestes** [comment]
I think the problem is that before now I didn't know that guide existed. In looking at the README for this repo, my eye jumped to the bulleted points on how to contribute, and the link to that file wasn't in there. I'm thinking maybe if that's just the first bullet point then it would be easier to see? Once I saw that file then I saw the bit about the `config.json`, but I think the problem is getting folks to see that file.

**Comment by kytrinyx** [comment]
Yeah, making it the first bullet point would probably be a good idea!

**Comment by parkerl** [comment]
Thanks 🎉

**Pull request merged**
