### PR TITLE
Create exercises subdir

### PR DESCRIPTION
**Pull request by Teapane**
Moves all exercises into the `exercises` subdirectory.  

[Addresses #96](https://github.com/exercism/xelixir/issues/96)

### CODE REVIEW

**Comment by Teapane** [comment]
I noticed that the `Travis` build just failed. I am not sure if this has to do with the `configlet` being updated yet or not.

**Comment by kytrinyx** [comment]
Configlet is supposed to be fixed, but there might be edge cases.

**Comment by kytrinyx** [comment]
Ah, nope:

```
The command "EXERCISM_TEST_EXAMPLES=true mix test --include pending **/*_test.exs" exited with 1.
```

Take a look at the `.travis.yml` file. I bet it just needs some extra stars in that command.

**Comment by kytrinyx** [comment]
Did you try running that command locally?

**Comment by Teapane** [comment]
I did. Hmm, fixing.

**Comment by parkerl** [comment]
@kytrinyx @Teapane I think there is something wrong in our test helpers. Had problems with this myself. Will try to take a look later.

**Comment by Teapane** [comment]
@parkerl sounds good, thanks! I'll take a look around as well.

**Comment by parkerl** [comment]
@Teapane I'm sure it's simple. Thanks for picking this up.

**Comment by Teapane** [comment]
It has to do with how `ExUnit` is finding `PATH` of the spec files. I am working on a fix but will close this for the time being. Thanks!

**Pull request closed without merging**
