### PR TITLE
Add difficulty ratings to `config.json`

### PR DESCRIPTION
**Pull request by devonestes**
This is my first attempt at adding the more precise difficulty raitings to the
new `config.json` structure. Of course they're super subjective, so feedback is
much appreciated!

This addresses point 2 of the open issue around updating to this new
`config.json` format.

### CODE REVIEW

**Comment by parkerl** [comment]
Looks good to me. Nice job, this is tough to figure out.

**Comment by martinsvalin** [comment]
Looks good. 👍

**Comment by devonestes** [comment]
@parkerl Think this is ready to roll, or should we leave this open a while longer for further comment?

**Comment by parkerl** [comment]
Let's do it! 🎉

**Pull request merged**
