### PR TITLE
Replace :pending test tag with idiomatic :skip tag

### PR DESCRIPTION
**Pull request by lpil**
Since Elixir v1.1 the tag `:skip` has been used to skip tests.

If we use the standard here the students will not have to re-learn how
to skip tests when they move onto real Elixir projects. :)

### CODE REVIEW

**Comment by devonestes** [comment]
I'm totally down with this - thanks for the great contribution! 👍 

Since it's a rather significant change I want to leave this open for a couple of days just to make sure no one raises any issues, but I can't see any myself.

**Comment by parkerl** [comment]
I'm :+1: on this change. I think it is great. However, it points out that the Elixir version in mix.exs is out of sync with the README and Travis. Opening an issue on that.

**Comment by lpil** [comment]
I can fix that. Would you like me to resolve it in this pull request or another?

**Comment by parkerl** [comment]
Normally I'd prefer a separate PR but since you have to change it in this one anyway let's do it here. Sound good?

**Comment by parkerl** [comment]
Thanks 🎉

**Pull request merged**
