### PR TITLE
Bob: add "asking in capitals" test

### PR DESCRIPTION
**Pull request by cbliard**
Bob answers 'Sure.' if you ask him a question, but what if yelling the question? Should Bob answer with "Sure." or "Whoa, chill out!"?

### CODE REVIEW

**Comment by parkerl** [comment]
@cbliard please update `example.exs` to pass this new test. Thanks!

**Comment by cbliard** [comment]
@parkerl Sorry I did not notice that the Travis checks failed the first time. It should be fixed now.

**Comment by parkerl** [comment]
No problem. Could you squash your commits please?

**Comment by cbliard** [comment]
Done.

I did not know about "squashing" when doing pull request. Glad to learn something :)

**Comment by parkerl** [comment]
Awesome! Thanks! 🎉

**Pull request merged**
