### PR TITLE
added in comments for beginning user clarity

### PR DESCRIPTION
**Pull request by Egogre**
Being brand new to elixir, it was confusing why the function def hello(name) was not found when running the test calling HelloWorld.hello() and get this error.
** (UndefinedFunctionError) undefined function: HelloWorld.hello/0

the "Your implementation goes here" also makes it seem like I should only have to change the inside of the function in order to get this to pass.

Instead of making a new empty argument function to show the passing test and then making another hello function that takes one argument, I changed the file to have comments to help guide a new user through their first elixir exercism.

Thanks also to @hectorhuertas for helping me through this!

### CODE REVIEW

**Comment by parkerl** [comment]
@kytrinyx I'm ok with this for the hello world. You?

**Comment by kytrinyx** [comment]
How about sticking this in a file named `HINTS.md`?

**Comment by kytrinyx** [comment]
Actually, I am OK with this for Hello World.

**Comment by Egogre** [comment]
@parkerl I am fine with putting the comments above def hello() or with making the hints.md file. Let me know what you would prefer!

**Comment by parkerl** [comment]
Please put them above. Thanks

**Comment by Egogre** [comment]
This has been done. I also squashed the commits.

**Comment by parkerl** [comment]
Hey @Egogre sorry for the delay...holidays. :blush: 

I don't see your updated commits. Did you push them?

**Comment by Egogre** [comment]
@parkerl Ah! Thanks! I had squashed them but didn't pay attention when I pushed. I am new to squashing so didn't realize it set my commit history back and then thought the origin branch was newer. I think it is ready now. Happy Holidays!

**Comment by parkerl** [comment]
Thanks! :tada:

**Pull request merged**
