### PR TITLE
Add hello-world exercise to Elixir track

### PR DESCRIPTION
**Pull request by bordeltabernacle**
The Hello, World! program is a classic introductory programming
exercise.  It hopefully provides a slightly gentler start to
learning Elixir, and introduces the Exercism concept to new users.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Yay, this addresses https://github.com/exercism/todo/issues/2

**Comment by bordeltabernacle** [comment]
oh, good! Didn't see that, sorry.

**Comment by kytrinyx** [comment]
You had no reason to see it, no apologies necessary.

**Comment by rubysolo** [comment]
:tada:

**Comment by bordeltabernacle** [comment]
Blowin' my mind.  What fun! Thankyou. :+1: :smiley:

**Pull request merged**
