### PR TITLE
Adds pending tags to specs in order to solve test by test

### PR DESCRIPTION
**Pull request by Lucasosf**
This is needed because it's a good idea spread the word of Test Driven Development (TDD) process.

Maybe is a good idea update the `README.md` file in order to explain this process, but I didn't find it to do it oO

Thank you :smile:

### CODE REVIEW

**Comment by Lucasosf** [comment]
ping @aarti @canweriotnow @kytrinyx

**Comment by kytrinyx** [comment]
@rubysolo and @pminten are the ones who are familiar with the elixir track.

**Comment by kytrinyx** [comment]
That said, it looks like we're moving towards a pending tag for all of the exercises. I'm comfortable merging this in if there's no response from Peter or Solomon in the next day or so.

**Comment by Lucasosf** [comment]
I see, thank you @kytrinyx. I will wait for them.

**Comment by rubysolo** [comment]
Looks good, thanks.

**Comment by Lucasosf** [comment]
Nice =D

**Pull request merged**
