### PR TITLE
Replaced last trailing space with "\s"

### PR DESCRIPTION
**Pull request by davbre**
Some editors automatically trim whitespace so I replaced the last trailing space with "\s".

### CODE REVIEW

**Comment by parkerl** [comment]
Nice, that is a good catch. Can you please squash your commits? Thanks!

**Comment by davbre** [comment]
@parkerl - from what I've read you can squash the two commits if/when you decide to merge. Is that the case? See here: [http://stackoverflow.com/a/36377634/10021400](http://stackoverflow.com/a/36377634/1002140).

**Comment by parkerl** [comment]
@davbre I can squash the commits. It does require me (or any maintainer) to fix up the commit message. (Sometimes I merge these simple PRs from a device where editing the message is a pain 😨 ) 

Thanks!
🎉

**Comment by davbre** [comment]
@parkerl - ok, thanks for doing that :+1: (I edited it online so you saved me the pain of cloning the rep locally etc)

**Pull request merged**
