### PR TITLE
Add tests for `up` in zipper exercism

### LINKED ISSUE #131: `up` function not tested in zipper exercism
`Zipper.up` is never used in the `zipper_text.exs` but the stub for it in the example is still there. I can write a couple tests for it and send those in, unless somebody else wants to that knows more about the exercises than me

### PR DESCRIPTION
**Pull request by dalexj**
closes #131

### CODE REVIEW

**Comment by rubysolo** [comment]
:+1: Thanks!

**Comment by parkerl** [comment]
Nice. :tada: 

@rubysolo do you think this test file should be more idiomatically formatted? Each pipe on a new line?

**Comment by dalexj** [comment]
from the perspective of somebody that just solved it: I read it just fine how it is and it all made sense in the tests.

**Comment by rubysolo** [comment]
I think these are fine.  The style guide discussions I have seen do indicate the left-alignment for multi-line pipelines, but also allow for single-line pipelines. (see https://github.com/niftyn8/elixir_style_guide/pull/33#issuecomment-72760481)

**Pull request merged**
